 version: '3'
 services:
   db:
     image: postgres:9.6.6
     network_mode: "host"
     container_name: dva-pg
     volumes:
      - dvapgdata:/var/lib/postgresql/data
     env_file:
       - ../common.env
   rabbit:
     image: rabbitmq
     network_mode: "host"
     container_name: dva-rmq
     env_file:
       - ../common.env
     volumes:
       - dvarabbit:/var/lib/rabbitmq
   redis:
     image: bitnami/redis:latest
     network_mode: "host"
     container_name: dva-redis
     env_file:
       - ../common.env
     volumes:
       - dvaredis:/bitnami
   dva:
     image: akshayubhat/dva-auto:latest
     network_mode: "host"
     container_name: webserver
     env_file:
       - ../common.env
     environment:
       - LAUNCH_NOTEBOOK=1
       - LAUNCH_SERVER_NGINX=1
       - LAUNCH_Q_GLOBAL_MODEL=1
       - LAUNCH_Q_GLOBAL_RETRIEVER=1
       - LAUNCH_BY_NAME_indexer_inception=1
       - LAUNCH_BY_NAME_indexer_facenet=1
       - LAUNCH_BY_NAME_retriever_inception=1
       - LAUNCH_BY_NAME_retriever_facenet=1
       - LAUNCH_BY_NAME_detector_coco=1
       - LAUNCH_BY_NAME_analyzer_crnn=1
       - LAUNCH_BY_NAME_analyzer_tagger=1
       - LAUNCH_BY_NAME_detector_face=1
       - LAUNCH_BY_NAME_detector_textbox=1
       - LAUNCH_Q_qextract=1
       - LAUNCH_Q_qstreamer=1
       - LAUNCH_Q_qtrainer=1
       - LAUNCH_SCHEDULER=1
       - INIT_PROCESS=/root/DVA/configs/custom_defaults/init_process.json
     command: bash -c "git reset --hard && git pull && sleep 10 && ./start_container.py"
     ports:
       - "localhost:80" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
       - "localhost:8888:8888" # Since Docker messes up iptables, ufw has no effect as a result bind to localhost and tunnel / Port forward through SSH
     depends_on:
       - db
       - rabbit
       - redis
     volumes:
       - dvadata:/root/media
 volumes:
  dvapgdata:
  dvadata:
  dvarabbit:
  dvaredis:
